name: Setup Node.js and PNPM
description: Setup Node.js and PNPM using asdf with caching

runs:
  using: composite
  steps:
    - name: Setup asdf
      uses: asdf-vm/actions/setup@v3

    - name: Install asdf plugins
      shell: bash
      run: |
        asdf plugin add nodejs
        asdf plugin add pnpm

    - name: Install tools from .tool-versions
      shell: bash
      run: asdf install

    - name: Get pnpm store directory
      shell: bash
      run: |
        echo "STORE_PATH=$(asdf exec pnpm store path --silent)" >> $GITHUB_ENV

    - name: Setup pnpm cache
      uses: actions/cache@v3
      with:
        path: ${{ env.STORE_PATH }}
        key: ${{ runner.os }}-pnpm-store-${{ hashFiles('**/pnpm-lock.yaml') }}
        restore-keys: |
          ${{ runner.os }}-pnpm-store-

    - name: Install dependencies
      shell: bash
      run: asdf exec pnpm install --frozen-lockfile
