import { writeFileSync } from 'fs';
import openapiTS from 'openapi-typescript';
import { resolve } from 'path';

const OPENAPI_SCHEMA_PATH = resolve('./src/backend/schema/openapi.json');
const OUTPUT_PATH = resolve('./src/frontend/types/api.ts');

async function generateApiTypes() {
  try {
    console.log('🔧 Generating API types from OpenAPI schema...');

    // Generate TypeScript types from OpenAPI schema
    const output = await openapiTS(OPENAPI_SCHEMA_PATH, {
      exportType: true,
      transform: {
        // Transform component names to be more TypeScript-friendly
        schema: (schema) => {
          // Keep original schema structure
          return schema;
        },
      },
    });

    // Add custom client types at the beginning
    const customTypes = `// Auto-generated API types from OpenAPI schema
// DO NOT EDIT - This file is automatically generated

export interface ApiResponse<T = unknown> {
  success: boolean;
  data?: T;
  error?: string;
  message?: string;
  cached?: boolean;
  total?: number;
  hasMore?: boolean;
}

export interface ApiError {
  error: string;
  message: string;
  details?: Array<{
    field: string;
    message: string;
  }>;
}

export interface RateLimitError {
  error: string;
  message: string;
  retryAfter: number;
}

// Configuration for different environments
export const API_CONFIG = {
  development: {
    baseURL: 'http://localhost:3001',
  },
  production: {
    baseURL: 'https://winette.vercel.app',
  },
} as const;

`;

    // Combine custom types with generated types
    const finalOutput = customTypes + '\n' + output;

    // Write the generated types to file
    writeFileSync(OUTPUT_PATH, finalOutput);

    console.log(`✅ API types generated successfully at ${OUTPUT_PATH}`);
  } catch (error) {
    console.error('❌ Failed to generate API types:', error);
    process.exit(1);
  }
}

// Run the script
generateApiTypes();
